targets:
  dev:  
    variables:
      env: dev
      num_workers: 1
      spark_version: r3.xlarge
      node_type_id: r3.xlarge
      DATABRICKS_HOST: https://calsaws-analytics-sbx-secure.cloud.databricks.com